version: '3.1'
services:
  mysql:
    image: mysql:8.0
    ports:
      - 3307:3306
    volumes:
      - /var/lib/app/aurora-manga/sql-data/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password