// Generated by https://quicktype.io

export interface PaypalSubscription {
  status:             string;
  status_update_time: string;
  id:                 string;
  plan_id:            string;
  start_time:         string;
  quantity:           string;
  shipping_amount:    ShippingAmount;
  subscriber:         Subscriber;
  billing_info:       BillingInfo;
  create_time:        string;
  update_time:        string;
  plan_overridden:    boolean;
  links:              Link[];
}

interface BillingInfo {
  outstanding_balance:   ShippingAmount;
  cycle_executions:      CycleExecution[];
  last_payment:          LastPayment;
  next_billing_time:     string;
  final_payment_time:    string;
  failed_payments_count: number;
}

interface CycleExecution {
  tenure_type:                    string;
  sequence:                       number;
  cycles_completed:               number;
  cycles_remaining:               number;
  current_pricing_scheme_version: number;
  total_cycles:                   number;
}

interface LastPayment {
  amount: ShippingAmount;
  time:   string;
}

interface ShippingAmount {
  currency_code: string;
  value:         string;
}

interface Link {
  href:   string;
  rel:    string;
  method: string;
}

interface Subscriber {
  email_address:    string;
  payer_id:         string;
  name:             Name;
  shipping_address: ShippingAddress;
}

interface Name {
  given_name: string;
  surname:    string;
}

interface ShippingAddress {
  address: Address;
}

interface Address {
  address_line_1: string;
  admin_area_2:   string;
  admin_area_1:   string;
  postal_code:    string;
  country_code:   string;
}
